PhotoArchiveCoilsWeb/Models/PhotoArchive.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoArchiveCoilsWeb.Models
{
    public class PhotoArchive
    {

        public Guid Id { get; set; }
        public string Cam { get; set; }
        public byte[] File { get; set; }
        public string ContentType { get; set; }
        public string Code { get; set; }
        public string Parent { get; set; }
        public string Description { get; set; }
        public DateTime CreatedTimestamp { get; set; }
        public DateTime UpdatedTimestamp { get; set; }
     
    }
}

PhotoArchiveCoilsWeb/Models/PhotoArchives.cs
using System;
using System.Collections.Generic;

namespace PhotoArchiveCoilsWeb.Models
{
    public partial class PhotoArchives
    {
        public Guid Id { get; set; }
        public string Cam { get; set; }
        public byte[] File { get; set; }
        public string ContentType { get; set; }
        public string Code { get; set; }
        public string Parent { get; set; }
        public string Description { get; set; }
        public DateTime CreatedTimestamp { get; set; }
        public DateTime UpdatedTimestamp { get; set; }
    }
}

PhotoArchiveCoilsWeb/Controllers/PhotoArchivesController.cs
using System;
using System.Drawing;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhotoArchiveCoilsWeb.Data;
using PhotoArchiveCoilsWeb.Models;
using System.Net;
using Microsoft.Extensions.Options;
using System.Threading;
using Microsoft.Extensions.Configuration;
using System.Web;

namespace PhotoArchiveCoilsWeb.Controllers
{
    public class PhotoArchivesController : Controller
    {
        private readonly FileContext _context;
        private readonly IOptions<ApplicationConfiguration> _optionsApplicationConfiguration;



        public PhotoArchivesController(FileContext context, IOptions<ApplicationConfiguration> o, IConfiguration config)
        {
            _context = context;
            _optionsApplicationConfiguration = o;

        }


        public IActionResult IndexCams()
        {
            //for (int i = 0; i < _optionsApplicationConfiguration.Value.Cams.Length; i++)
            //{
            //    if (ImageSave.Instance().connection != null)
            //    {
            //        //await ImageSave.Instance().ImageSaveAsync(_optionsApplicationConfiguration.Value.Cams[i]);

            //    }
            //}

            return View(_optionsApplicationConfiguration.Value.Cams);
        }

        public async Task<IEnumerable<PhotoArchiveShort>> GetAllFiles()
        {
            //var items = _context.PhotoArchives.OrderByDescending(u => u.CreatedTimestamp).Take(2);
            //_context.PhotoArchives.Select

            return await _context.PhotoArchives.OrderByDescending(u => u.CreatedTimestamp).Take(100).Select(
                    photoArchive => new PhotoArchiveShort
                    {
                        Id = photoArchive.Id,
                        Parent = photoArchive.Parent,
                        Cam = photoArchive.Cam,
                        Code = photoArchive.Code,
                        Description = photoArchive.Description,
                        CreatedTimestamp = photoArchive.CreatedTimestamp,
                        UpdatedTimestamp = photoArchive.UpdatedTimestamp
                    }).ToListAsync();



        }

        // GET: PhotoArchives
        public async Task<IActionResult> Index()
        {
            // return View(await _context.PhotoArchives.ToListAsync());

            //var model = new AllUploadedFiles { PhotoArchiveShorts = GetAllFiles().ToList() };
            //return View(model);
            //return View(GetAllFiles().ToList());
            //return View(await _context.PhotoArchivesShort.ToListAsync());
            return View(await GetAllFiles());
        }

        public FileResult GetFileFromBytes(byte[] bytesIn)
        {
            return File(bytesIn, "image/jpg");
        }

        [HttpGet]
        public async Task<IActionResult> GetUserImageFile(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photoArchive = await _context.PhotoArchives
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photoArchive == null)
            {
                return NotFound();
            }
            /*
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return null;
            }
            */
            //FileResult imageUserFile = GetFileFromBytes(photoArchive.File);
            //return imageUserFile;
            return File(photoArchive.File, photoArchive.ContentType);
        }
        public IActionResult GetLoadImage(String id)
        {
            //Console.WriteLine("cerco cam con url "+ HttpUtility.UrlDecode(id));
            var cam = new Cam();
            for (int i = 0; i < _optionsApplicationConfiguration.Value.Cams.Length; i++)
            {
                //Console.WriteLine("controllo cam con url " + _optionsApplicationConfiguration.Value.Cams[i].Url);
                if (_optionsApplicationConfiguration.Value.Cams[i].Url == HttpUtility.UrlDecode(id))
                {
                    cam = _optionsApplicationConfiguration.Value.Cams[i];
                    break;
                }
            }

            if (cam != null)
            {
                WebRequest req = WebRequest.Create(cam.Url);
                req.Credentials = new NetworkCredential(cam.UserName, cam.Password);
                WebResponse resp = req.GetResponse();
                string contentType = "";
                if (resp != null)
                {
                    Stream img = resp.GetResponseStream();
                    contentType = resp.ContentType;
                    return File(img, contentType);
                }
            }
            return null;
        }

        // GET: PhotoArchives/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photoArchive = await _context.PhotoArchives
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photoArchive == null)
            {
                return NotFound();
            }
            PhotoArchiveShort photoArchiveShort = new PhotoArchiveShort();
            photoArchiveShort.Id = photoArchive.Id;
            photoArchiveShort.Parent = photoArchive.Parent;
            photoArchiveShort.Cam = photoArchive.Cam;
            photoArchiveShort.Code = photoArchive.Code;
            photoArchiveShort.Description = photoArchive.Description;
            photoArchiveShort.CreatedTimestamp = photoArchive.CreatedTimestamp;
            photoArchiveShort.UpdatedTimestamp = photoArchive.UpdatedTimestamp;
            return View(photoArchiveShort);
        }

        // GET: PhotoArchives/DetailsCode/5
        [HttpPost]
        public async Task<IActionResult> DetailsCode(string Code)
        {
            Console.WriteLine("Details code: " + Code);
            if (Code == null)
            {
                return NotFound();
            }

            var photoArchive = await _context.PhotoArchives
                .FirstOrDefaultAsync(m => m.Code == Code);
            if (photoArchive == null)
            {
                return NotFound();
            }
            PhotoArchiveShort photoArchiveShort = new PhotoArchiveShort();
            photoArchiveShort.Id = photoArchive.Id;
            photoArchiveShort.Parent = photoArchive.Parent;
            photoArchiveShort.Cam = photoArchive.Cam;
            photoArchiveShort.Code = photoArchive.Code;
            photoArchiveShort.Description = photoArchive.Description;
            photoArchiveShort.CreatedTimestamp = photoArchive.CreatedTimestamp;
            photoArchiveShort.UpdatedTimestamp = photoArchive.UpdatedTimestamp;
            //return View(photoArchiveShort);
            return View("Details", photoArchiveShort);
        }

        // GET: PhotoArchives/Create
        public async Task<IActionResult> Create()
        {
            Console.WriteLine("Numero di telecamere configurate: " + _optionsApplicationConfiguration.Value.Cams.Length);

            for (int i = 0; i < _optionsApplicationConfiguration.Value.Cams.Length; i++)
            {

                await ImageSave.Instance().ImageSaveAsync(_optionsApplicationConfiguration.Value.Cams[i]);


            }
            //return View();
            return RedirectToAction(nameof(Index));
        }

        /*
                // POST: PhotoArchives/Create
                // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
                // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
                [HttpPost]
                [ValidateAntiForgeryToken]
                public async Task<IActionResult> Create([Bind("Id,Cam,File,Code,Parent,Description,CreatedTimestamp,UpdatedTimestamp")] PhotoArchive photoArchive)
                {
                    if (ModelState.IsValid)
                    {
                        _context.Add(photoArchive);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    return View(photoArchive);
                }
                */

        // GET: PhotoArchives/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photoArchive = await _context.PhotoArchives.FindAsync(id);
            if (photoArchive == null)
            {
                return NotFound();
            }

            //return View(photoArchive);
            PhotoArchiveEdit photoArchiveEdit = new PhotoArchiveEdit();
            photoArchiveEdit.Id = photoArchive.Id;
            photoArchiveEdit.Description = photoArchive.Description;

            return View(photoArchiveEdit);
        }

        // POST: PhotoArchives/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(Guid id, [Bind("Id,Description")] PhotoArchiveEdit photoArchiveEdit)
        {
            if (id != photoArchiveEdit.Id)
            {
                return NotFound();
            }
            /*
            PhotoArchive photoArchive2 = new PhotoArchive();

PhotoArchiveCoilsWeb/Views/PhotoArchives/Create.cshtml
@model PhotoArchiveCoilsWeb.Models.PhotoArchive

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PhotoArchive</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cam" class="control-label"></label>
                <input asp-for="Cam" class="form-control" />
                <span asp-validation-for="Cam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parent" class="control-label"></label>
                <input asp-for="Parent" class="form-control" />
                <span asp-validation-for="Parent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedTimestamp" class="control-label"></label>
                <input asp-for="CreatedTimestamp" class="form-control" />
                <span asp-validation-for="CreatedTimestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedTimestamp" class="control-label"></label>
                <input asp-for="UpdatedTimestamp" class="form-control" />
                <span asp-validation-for="UpdatedTimestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoArchiveCoilsWeb/Views/PhotoArchives/Delete.cshtml
@model PhotoArchiveCoilsWeb.Models.PhotoArchive

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PhotoArchive</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.File)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.File)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedTimestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedTimestamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedTimestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedTimestamp)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PhotoArchiveCoilsWeb/Views/PhotoArchives/Details.cshtml
@model PhotoArchiveCoilsWeb.Models.PhotoArchiveShort

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PhotoArchive</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Parent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Parent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedTimestamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedTimestamp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedTimestamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedTimestamp)
        </dd>
    </dl>
</div>
<img src='@Url.Action("GetUserImageFile", "PhotoArchives", new { id = Model.Id })' class="img-fluid" alt="Responsive image"/>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PhotoArchiveCoilsWeb/Views/PhotoArchives/Edit.cshtml
@model PhotoArchiveCoilsWeb.Models.PhotoArchiveEdit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PhotoArchive</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoArchiveCoilsWeb/Views/PhotoArchives/Index.cshtml
@model IEnumerable<PhotoArchiveCoilsWeb.Models.PhotoArchiveShort>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>

        <form asp-controller="PhotoArchives" asp-action="DetailsCode">
            <p>
                Code: <input type="text" name="Code">
                <input type="submit" value="Search Code" />
            </p>
        </form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedTimestamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedTimestamp)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedTimestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedTimestamp)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                <!--
                |<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                -->
            </td>
        </tr>
}
    </tbody>
</table>
<meta http-equiv="refresh" content="10">

PhotoArchiveCoilsWeb/Views/PhotoArchives/IndexCams.cshtml
@model IEnumerable<PhotoArchiveCoilsWeb.Cam>

@{
    ViewData["Title"] = "Index Cams";
}


<body>
    <!-- The main container DIV starts here -->
    <div class="container">
        <div class="row">
            <!--First row containing the main Heading-->
            <div class="col-lg-12">
                <h1 class="page-header">Welcome in PhotoArchiveCoils</h1>
                <p>Cams configurated</a>.</p>
            </div>
            @foreach (var item in Model)
            {
                <!--Next row containing the respective images in 3x4 grids starts here -->
                <div class="col-md-4">
                    <div class="thumbnail">
                        <a> @Html.DisplayFor(modelItem => item.Name)</a>
                        <img src='@Url.Action("GetLoadImage", "PhotoArchives", new { id = item.Url })' class="img-fluid" alt="Responsive image" />
                    </div>
                </div>
            }
        </div>
            </div>
</body>
<meta http-equiv="refresh" content="5">